"""company self

Revision ID: 6a4ee8bd2f04
Revises: dee5fd8c3d00
Create Date: 2023-05-30 03:37:33.554455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4ee8bd2f04'
down_revision = 'dee5fd8c3d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
