"""company_dev_table3

Revision ID: dee5fd8c3d00
Revises: d49fdb503059
Create Date: 2023-05-30 00:49:21.236495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee5fd8c3d00'
down_revision = 'd49fdb503059'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
